#!/usr/bin/env python3
"""Generate the bundled QML-friendly emoji catalog from Emote's CSV."""

import csv
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "data" / "emojis.csv"
OUTPUT = ROOT / "emoji-data.js"

BLOCKED_GROUPS = {"component", "extras-openmoji", "extras-unicode"}
CATEGORY_NAMES = {
    "recent": "Recently Used",
    "smileys-people": "Smileys & People",
    "animals-nature": "Animals & Nature",
    "food-drink": "Food & Drink",
    "activities": "Activities",
    "travel-places": "Travel & Places",
    "objects": "Objects",
    "symbols": "Symbols",
    "flags": "Flags",
}


def keywords(row):
    values = []
    for field in ("annotation", "tags", "openmoji_tags"):
        values.extend(part.strip().lower() for part in row[field].split(","))
    return sorted({value for value in values if value})


def main():
    rows = []
    base_to_variants = {}
    with INPUT.open(encoding="utf-8", newline="") as source:
        for row in csv.DictReader(source):
            rows.append(row)
            st = row["skintone"]
            base = row["skintone_base_emoji"]
            if st in {"1", "2", "3", "4", "5"} and base:
                if base not in base_to_variants:
                    base_to_variants[base] = {}
                base_to_variants[base][int(st)] = row["emoji"]

    entries = []
    seen = set()
    for row in rows:
        group = row["group"]
        if group in BLOCKED_GROUPS or row["skintone"] or not row["emoji"]:
            continue
        category = "smileys-people" if group in {"smileys-emotion", "people-body"} else group
        if category not in CATEGORY_NAMES or row["emoji"] in seen:
            continue
        seen.add(row["emoji"])
        entry = {
            "emoji": row["emoji"],
            "name": row["annotation"].capitalize(),
            "keywords": keywords(row),
            "category": category,
        }
        if row["emoji"] in base_to_variants:
            ts = base_to_variants[row["emoji"]]
            entry["variants"] = [ts.get(i) for i in range(1, 6)]
        entries.append(entry)

    output = "// Generated by scripts/build_catalog.py from Emote's static/emojis.csv.\n"
    output += "var entries = " + json.dumps(entries, ensure_ascii=False, separators=(",", ":")) + ";\n"
    output += "var categories = " + json.dumps(CATEGORY_NAMES, ensure_ascii=False, separators=(",", ":")) + ";\n"
    output += "function getEntries() { return entries; }\n"
    output += "function getCategories() { return categories; }\n"
    OUTPUT.write_text(output, encoding="utf-8")
    print(f"Generated {len(entries)} emoji entries ({sum(1 for e in entries if 'variants' in e)} with skin variants)")


if __name__ == "__main__":
    main()
